image: openjdk:17-jdk

stages:
  - setup
  - build

before_script:
  - GRADLE_USER_HOME="$(pwd)/.gradle"
  - export GRADLE_USER_HOME

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches
    - build/*
    - projects/*

setup:
  stage: setup
  script:
    - chmod +x gradlew && ./gradlew setup
  except:
    - tags

build:
  stage: build
  script:
    - chmod +x gradlew && ./gradlew magmaJar
    - echo "VERSION=$(./gradlew -q | grep 'Forge Version:' | awk '{print $3}')" >> variables.env
  artifacts:
    reports:
      dotenv: variables.env
    paths:
      - projects/magma/build/libs/*server*.jar
  except:
    - tags

after_script:
  - echo "End CI"
