name: PR-Build
on: [pull_request]
jobs:
  build:
    if: "! contains(toJSON(github.event.commits.*.message), '[ci skip]')"
    runs-on: ubuntu-20.04
    container:
      image: openjdk:17-jdk
    steps:
      - uses: actions/checkout@v1
      - uses: gradle/wrapper-validation-action@v1.0.3
      - run: chmod +x ./gradlew
      - run: ./gradlew setup installerJar
        env:
          STABLE_BUILD: 0
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v2.2.2
        with:
          name: Builds
          path: projects/magma/build/libs/*installer*.jar
